CREATE TABLE IF NOT EXISTS JOGO (
ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
DATA_HORA_JOGO DATE, 
GOLS_VISITANTE INTEGER, 
GOLS_CASA INTEGER, 
ID_TIME_CASA INTEGER, 
ID_TIME_VISITANTE INTEGER, 
ID_ESTADIO INTEGER, 
ID_CAMPEONATO INTEGER
);